name: 'Bina Static Analysis'
description: 'Deterministic, rule-based static analysis for Python code.'
author: 'Bina Team'
branding:
  icon: 'eye'
  color: 'blue'

inputs:
  path:
    description: 'Path to scan'
    required: false
    default: '.'
  fail_on_high:
    description: 'Fail CI if HIGH severity issues are found'
    required: false
    default: 'true'
  config_path:
    description: 'Path to configuration file'
    default: 'bina.yaml'
  baseline_path:
    description: 'Path to baseline file'
    default: 'bina-report-baseline.json'
  token:
    description: 'GitHub Token for posting comments'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Bina
      run: pip install ${{ github.action_path }}
      shell: bash

    - name: Run Bina
      run: |
        # 1. Run Analysis and generate JSON
        # We always generate JSON for the report step
        bina check ${{ inputs.path }} \
          --config ${{ inputs.config_path }} \
          --baseline ${{ inputs.baseline_path }} \
          --json > bina_output.json
        
        # Capture exit code? Bina --json typically runs clean and outputs logs.
        # But if fail-on-high is needed, we usually exit code 1.
        # However, `bina check` without --json prints table and exits status code 1 if issues found.
        # With --json, `bina check` should print json to stdout.
        # It currently `click.echo(json.dumps)` AND `exit(1)`? No, see cli.py.
        # `if json_output: ... click.echo ... else: ... exit(1)`
        # Wait, if issues found in JSON mode, does it exit 1?
        # Let's check CLI implementation I wrote.
        # ... `if json_output: ... click.echo ...` -> It ends function. Implicit return None.
        # So it exits 0! This is good for pipeline continuation to reporting step.
        
        # 2. Print Table to Console
        if [ -f bina_output.json ]; then
            echo "::group::Bina Analysis Report"
            bina view-report bina_output.json
            echo "::endgroup::"
        fi
        
        # 3. Post Report to GitHub (Only on PRs)
        if [ "${{ github.event_name }}" == "pull_request" ]; then
            export GITHUB_TOKEN="${{ inputs.token }}"
            export GITHUB_PR_NUMBER="${{ github.event.pull_request.number }}"
            
            if [ -f bina_output.json ]; then
                bina ci-report bina_output.json --baseline ${{ inputs.baseline_path }}
            fi
        fi
        
        # 4. Fail if needed (Fail on High)
        if [ "${{ inputs.fail_on_high }}" == "true" ]; then
             # Parse JSON to check for HIGH severity?
             # Simple python oneliner using the generated file
             python3 -c "import json, sys; findings=json.load(open('bina_output.json')); sys.exit(1 if any(f.get('severity') == 'HIGH' for f in findings) else 0)"
        fi
      shell: bash
