name: 'Bina Static Analysis'
description: 'Deterministic, rule-based static analysis for Python code.'
author: 'Bina Team'
branding:
  icon: 'eye'
  color: 'blue'

inputs:
  path:
    description: 'Path to scan'
    required: false
    default: '.'
  fail_on_high:
    description: 'Fail CI if HIGH severity issues are found'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Bina
      run: pip install ${{ github.action_path }}
      shell: bash

    - name: Run Bina
      run: |
        # Run bina and capture output
        bina check ${{ inputs.path }} --json > bina_report.json
        
        # Parse JSON and create annotations
        python3 - <<EOF
        import json
        import sys

        try:
            with open('bina_report.json') as f:
                findings = json.load(f)

            fail_workflow = False
            for f in findings:
                severity = f['severity']
                # Map to GitHub annotation levels: notice, warning, failure
                level = 'notice'
                if severity == 'MEDIUM':
                    level = 'warning'
                elif severity == 'HIGH':
                    level = 'error'
                    # Note: We must be careful with boolean injection from inputs in python
                    if '${{ inputs.fail_on_high }}' == 'true':
                        fail_workflow = True

                # Fix: Use proper quoting for f-string and keys
                msg = f['message']
                r_id = f['rule_id']
                fname = f['file']
                line = f['line']
                col = f['column']
                print(f"::{level} file={fname},line={line},col={col},title={r_id}::{msg}")

            if fail_workflow:
                sys.exit(1)
        except Exception as e:
            print(e)
            sys.exit(1)
        EOF
      shell: bash
